export const REQUEST_DATA="REQUEST_DATA";
export const POST_SUCCESS_DATA="SUCCESS_DATA";
export const FAILURE_DATA="FAILURE_DATA";
export const GET_SUCCESS_DATA="GET_SUCCESS_DATA";
export const GET_COUNTS_DATA="GET_COUNTS_DATA";
export const GET_CHARTS_DATA="GET_CHARTS_DATA";